### ISSUE TITLE
Should the status "not to be annotated" be editable after the upload?

### ISSUE THREAD

**Issue by 12Balu34** [Hajeong-Noh/20180505_AWT-project#18]

**Comment by 12Balu34** [comment]
Should be editable, but only if status is "created". NOT after it has been started (or closed)

**Comment by Hajeong-Noh** [comment]
But... what if a manager uploaded two duplicate peaks, one with "to be annotated" and one with "not to be annotated". And then the manager wants to change the status of a peak.
