### ISSUE TITLE
Build peak endpoints

### ISSUE THREAD

**Issue by Hajeong-Noh** [Hajeong-Noh/20180505_AWT-project#30]
- [x] GET /api/peaks *Showing list of peaks depending on the role*
- [x] GET /api/peaks/{id} *Showing a single peak*
- [x] POST /api/peaks *Uploading new peak data for a campaign*
- [x] PATCH /api/peaks/{id} *Changing the "to be annotated" status (ATTENTION: only if the associated campaign is in CREATED status)*

**Comment by 12Balu34** [comment]
We should rethink the endpoints. Each campaign/peak should have a unique Url

**Comment by Hajeong-Noh** [comment]
/api/campaigns/{id}
/api/peaks/{id}

Aren't they unique?
