### ISSUE TITLE
What happens if a manager loads two different dataset that has a same data point in a single campaign?

### ISSUE THREAD

**Issue by Hajeong-Noh** [Hajeong-Noh/20180505_AWT-project#5]

**Comment by 12Balu34** [comment]
we'll get updates soon

**Comment by 12Balu34** [comment]
**Reply by the TA:**

We talked with the professor, and he said that it is ok to upload one file to annotate peaks, one file of peaks to do not annotate them.
All the peaks (even if they have the same values for the tuple id-provenance) can be treated as different peaks. If you want to implement all the functionality that will handle the cases of duplicated peaks in the database, you can do it, but t**his is not required.**
