### ISSUE TITLE
Worker Sign Up

### ISSUE THREAD

**Issue by Hajeong-Noh** [Hajeong-Noh/20180505_AWT-project#9]
As a worker,
I want to sign up
so that I can create annotations

- [ ] There is a field for confirming password again
- [ ] Username should be unique
- [ ] Password should be hidden on the screen
- [ ] E-mail address should be validated
- [ ] Radio button for choosing a role (Manager or Worker)

**Comment by 12Balu34** [comment]
Merged with issue #8
